const tarotDeck = [
  { id: 0, name: "Deli", image: "0_deli.webp" },
  { id: 1, name: "Büyücü", image: "1_buyucu.webp" },
  { id: 2, name: "Başrahibe", image: "2_basrahibe.webp" },
  { id: 3, name: "İmparatoriçe", image: "3_imparatorice.webp" },
  { id: 4, name: "İmparator", image: "4_imparator.webp" },
  { id: 5, name: "Aziz", image: "5_aziz.webp" },
  { id: 6, name: "Aşıklar", image: "6_asiklar.webp" },
  { id: 7, name: "Savaş Arabası", image: "7_savas_arabasi.webp" },
  { id: 8, name: "Güç", image: "8_guc.webp" },
  { id: 9, name: "Ermiş", image: "9_ermis.webp" },
  { id: 10, name: "Kader Çarkı", image: "10_kader_carki.webp" },
  { id: 11, name: "Adalet", image: "11_adalet.webp" },
  { id: 12, name: "Asılan Adam", image: "12_asilan_adam.webp" },
  { id: 13, name: "Ölüm", image: "13_olum.webp" },
  { id: 14, name: "Denge", image: "14_denge.webp" },
  { id: 15, name: "Şeytan", image: "15_seytan.webp" },
  { id: 16, name: "Kule", image: "16_kule.webp" },
  { id: 17, name: "Yıldız", image: "17_yildiz.webp" },
  { id: 18, name: "Ay", image: "18_ay.webp" },
  { id: 19, name: "Güneş", image: "19_gunes.webp" },
  { id: 20, name: "Mahkeme", image: "20_mahkeme.webp" },
  { id: 21, name: "Dünya", image: "21_dunya.webp" },

  { id: 22, name: "Değnek Ası", image: "22_degnek_asi.webp" },
  { id: 23, name: "Değnek İkilisi", image: "23_degnek_ikilisi.webp" },
  { id: 24, name: "Değnek Üçlüsü", image: "24_degnek_uclusu.webp" },
  { id: 25, name: "Değnek Dörtlüsü", image: "25_degnek_dortlusu.webp" },
  { id: 26, name: "Değnek Beşlisi", image: "26_degnek_beslisi.webp" },
  { id: 27, name: "Değnek Altılısı", image: "27_degnek_altilisi.webp" },
  { id: 28, name: "Değnek Yedilisi", image: "28_degnek_yedilisi.webp" },
  { id: 29, name: "Değnek Sekizlisi", image: "29_degnek_sekizlisi.webp" },
  { id: 30, name: "Değnek Dokuzlusu", image: "30_degnek_dokuzlusu.webp" },
  { id: 31, name: "Değnek Onlusu", image: "31_degnek_onlusu.webp" },
  { id: 32, name: "Değnek Uşağı", image: "32_degnek_usagi.webp" },
  { id: 33, name: "Değnek Şövalyesi", image: "33_degnek_sovalyesi.webp" },
  { id: 34, name: "Değnek Kraliçesi", image: "34_degnek_kralicesi.webp" },
  { id: 35, name: "Değnek Kralı", image: "35_degnek_kralı.webp" },

  { id: 36, name: "Kupa Ası", image: "36_kupa_asi.webp" },
  { id: 37, name: "Kupa İkilisi", image: "37_kupa_ikilisi.webp" },
  { id: 38, name: "Kupa Üçlüsü", image: "38_kupa_uclusu.webp" },
  { id: 39, name: "Kupa Dörtlüsü", image: "39_kupa_dortlusu.webp" },
  { id: 40, name: "Kupa Beşlisi", image: "40_kupa_beslisi.webp" },
  { id: 41, name: "Kupa Altılısı", image: "41_kupa_altilisi.webp" },
  { id: 42, name: "Kupa Yedilisi", image: "42_kupa_yedilisi.webp" },
  { id: 43, name: "Kupa Sekizlisi", image: "43_kupa_sekizlisi.webp" },
  { id: 44, name: "Kupa Dokuzlusu", image: "44_kupa_dokuzlusu.webp" },
  { id: 45, name: "Kupa Onlusu", image: "45_kupa_onlusu.webp" },
  { id: 46, name: "Kupa Uşağı", image: "46_kupa_usagi.webp" },
  { id: 47, name: "Kupa Şövalyesi", image: "47_kupa_sovalyesi.webp" },
  { id: 48, name: "Kupa Kraliçesi", image: "48_kupa_kralicesi.webp" },
  { id: 49, name: "Kupa Kralı", image: "49_kupa_kralı.webp" },

  { id: 50, name: "Kılıç Ası", image: "50_kilic_asi.webp" },
  { id: 51, name: "Kılıç İkilisi", image: "51_kilic_ikilisi.webp" },
  { id: 52, name: "Kılıç Üçlüsü", image: "52_kilic_uclusu.webp" },
  { id: 53, name: "Kılıç Dörtlüsü", image: "53_kilic_dortlusu.webp" },
  { id: 54, name: "Kılıç Beşlisi", image: "54_kilic_beslisi.webp" },
  { id: 55, name: "Kılıç Altılısı", image: "55_kilic_altilisi.webp" },
  { id: 56, name: "Kılıç Yedilisi", image: "56_kilic_yedilisi.webp" },
  { id: 57, name: "Kılıç Sekizlisi", image: "57_kilic_sekizlisi.webp" },
  { id: 58, name: "Kılıç Dokuzlusu", image: "58_kilic_dokuzlusu.webp" },
  { id: 59, name: "Kılıç Onlusu", image: "59_kilic_onlusu.webp" },
  { id: 60, name: "Kılıç Uşağı", image: "60_kilic_usagi.webp" },
  { id: 61, name: "Kılıç Şövalyesi", image: "61_kilic_sovalyesi.webp" },
  { id: 62, name: "Kılıç Kraliçesi", image: "62_kilic_kralicesi.webp" },
  { id: 63, name: "Kılıç Kralı", image: "63_kilic_kralı.webp" },

  { id: 64, name: "Tılsım Ası", image: "64_tilsim_asi.webp" },
  { id: 65, name: "Tılsım İkilisi", image: "65_tilsim_ikilisi.webp" },
  { id: 66, name: "Tılsım Üçlüsü", image: "66_tilsim_uclusu.webp" },
  { id: 67, name: "Tılsım Dörtlüsü", image: "67_tilsim_dortlusu.webp" },
  { id: 68, name: "Tılsım Beşlisi", image: "68_tilsim_beslisi.webp" },
  { id: 69, name: "Tılsım Altılısı", image: "69_tilsim_altilisi.webp" },
  { id: 70, name: "Tılsım Yedilisi", image: "70_tilsim_yedilisi.webp" },
  { id: 71, name: "Tılsım Sekizlisi", image: "71_tilsim_sekizlisi.webp" },
  { id: 72, name: "Tılsım Dokuzlusu", image: "72_tilsim_dokuzlusu.webp" },
  { id: 73, name: "Tılsım Onlusu", image: "73_tilsim_onlusu.webp" },
  { id: 74, name: "Tılsım Uşağı", image: "74_tilsim_usagi.webp" },
  { id: 75, name: "Tılsım Şövalyesi", image: "75_tilsim_sovalyesi.webp" },
  { id: 76, name: "Tılsım Kraliçesi", image: "76_tilsim_kralicesi.webp" },
  { id: 77, name: "Tılsım Kralı", image: "77_tilsim_kralı.webp" }
];

export const getTarotById = (id) =>
  tarotDeck.find(card => card.id === id);

export { tarotDeck };