const tarotDeck = [
  { id: 0, name: "Deli", image: "assets/tarot/0_deli.webp" },
  { id: 1, name: "Büyücü", image: "assets/tarot/1_buyucu.webp" },
  { id: 2, name: "Başrahibe", image: "assets/tarot/2_basrahibe.webp" },
  { id: 3, name: "İmparatoriçe", image: "assets/tarot/3_imparatorice.webp" },
  { id: 4, name: "İmparator", image: "assets/tarot/4_imparator.webp" },
  { id: 5, name: "Aziz", image: "assets/tarot/5_aziz.webp" },
  { id: 6, name: "Aşıklar", image: "assets/tarot/6_asiklar.webp" },
  { id: 7, name: "Savaş Arabası", image: "assets/tarot/7_savas_arabasi.webp" },
  { id: 8, name: "Güç", image: "assets/tarot/8_guc.webp" },
  { id: 9, name: "Ermiş", image: "assets/tarot/9_ermis.webp" },
  { id: 10, name: "Kader Çarkı", image: "assets/tarot/10_kader_carki.webp" },
  { id: 11, name: "Adalet", image: "assets/tarot/11_adalet.webp" },
  { id: 12, name: "Asılan Adam", image: "assets/tarot/12_asilan_adam.webp" },
  { id: 13, name: "Ölüm", image: "assets/tarot/13_olum.webp" },
  { id: 14, name: "Denge", image: "assets/tarot/14_denge.webp" },
  { id: 15, name: "Şeytan", image: "assets/tarot/15_seytan.webp" },
  { id: 16, name: "Kule", image: "assets/tarot/16_kule.webp" },
  { id: 17, name: "Yıldız", image: "assets/tarot/17_yildiz.webp" },
  { id: 18, name: "Ay", image: "assets/tarot/18_ay.webp" },
  { id: 19, name: "Güneş", image: "assets/tarot/19_gunes.webp" },
  { id: 20, name: "Mahkeme", image: "assets/tarot/20_mahkeme.webp" },
  { id: 21, name: "Dünya", image: "assets/tarot/21_dunya.webp" },

  { id: 22, name: "Değnek Ası", image: "assets/tarot/22_degnek_asi.webp" },
  { id: 23, name: "Değnek İkilisi", image: "assets/tarot/23_degnek_ikilisi.webp" },
  { id: 24, name: "Değnek Üçlüsü", image: "assets/tarot/24_degnek_uclusu.webp" },
  { id: 25, name: "Değnek Dörtlüsü", image: "assets/tarot/25_degnek_dortlusu.webp" },
  { id: 26, name: "Değnek Beşlisi", image: "assets/tarot/26_degnek_beslisi.webp" },
  { id: 27, name: "Değnek Altılısı", image: "assets/tarot/27_degnek_altilisi.webp" },
  { id: 28, name: "Değnek Yedilisi", image: "assets/tarot/28_degnek_yedilisi.webp" },
  { id: 29, name: "Değnek Sekizlisi", image: "assets/tarot/29_degnek_sekizlisi.webp" },
  { id: 30, name: "Değnek Dokuzlusu", image: "assets/tarot/30_degnek_dokuzlusu.webp" },
  { id: 31, name: "Değnek Onlusu", image: "assets/tarot/31_degnek_onlusu.webp" },
  { id: 32, name: "Değnek Uşağı", image: "assets/tarot/32_degnek_usagi.webp" },
  { id: 33, name: "Değnek Şövalyesi", image: "assets/tarot/33_degnek_sovalyesi.webp" },
  { id: 34, name: "Değnek Kraliçesi", image: "assets/tarot/34_degnek_kralicesi.webp" },
  { id: 35, name: "Değnek Kralı", image: "assets/tarot/35_degnek_kralı.webp" },

  { id: 36, name: "Kupa Ası", image: "assets/tarot/36_kupa_asi.webp" },
  { id: 37, name: "Kupa İkilisi", image: "assets/tarot/37_kupa_ikilisi.webp" },
  { id: 38, name: "Kupa Üçlüsü", image: "assets/tarot/38_kupa_uclusu.webp" },
  { id: 39, name: "Kupa Dörtlüsü", image: "assets/tarot/39_kupa_dortlusu.webp" },
  { id: 40, name: "Kupa Beşlisi", image: "assets/tarot/40_kupa_beslisi.webp" },
  { id: 41, name: "Kupa Altılısı", image: "assets/tarot/41_kupa_altilisi.webp" },
  { id: 42, name: "Kupa Yedilisi", image: "assets/tarot/42_kupa_yedilisi.webp" },
  { id: 43, name: "Kupa Sekizlisi", image: "assets/tarot/43_kupa_sekizlisi.webp" },
  { id: 44, name: "Kupa Dokuzlusu", image: "assets/tarot/44_kupa_dokuzlusu.webp" },
  { id: 45, name: "Kupa Onlusu", image: "assets/tarot/45_kupa_onlusu.webp" },
  { id: 46, name: "Kupa Uşağı", image: "assets/tarot/46_kupa_usagi.webp" },
  { id: 47, name: "Kupa Şövalyesi", image: "assets/tarot/47_kupa_sovalyesi.webp" },
  { id: 48, name: "Kupa Kraliçesi", image: "assets/tarot/48_kupa_kralicesi.webp" },
  { id: 49, name: "Kupa Kralı", image: "assets/tarot/49_kupa_kralı.webp" },

  { id: 50, name: "Kılıç Ası", image: "assets/tarot/50_kilic_asi.webp" },
  { id: 51, name: "Kılıç İkilisi", image: "assets/tarot/51_kilic_ikilisi.webp" },
  { id: 52, name: "Kılıç Üçlüsü", image: "assets/tarot/52_kilic_uclusu.webp" },
  { id: 53, name: "Kılıç Dörtlüsü", image: "assets/tarot/53_kilic_dortlusu.webp" },
  { id: 54, name: "Kılıç Beşlisi", image: "assets/tarot/54_kilic_beslisi.webp" },
  { id: 55, name: "Kılıç Altılısı", image: "assets/tarot/55_kilic_altilisi.webp" },
  { id: 56, name: "Kılıç Yedilisi", image: "assets/tarot/56_kilic_yedilisi.webp" },
  { id: 57, name: "Kılıç Sekizlisi", image: "assets/tarot/57_kilic_sekizlisi.webp" },
  { id: 58, name: "Kılıç Dokuzlusu", image: "assets/tarot/58_kilic_dokuzlusu.webp" },
  { id: 59, name: "Kılıç Onlusu", image: "assets/tarot/59_kilic_onlusu.webp" },
  { id: 60, name: "Kılıç Uşağı", image: "assets/tarot/60_kilic_usagi.webp" },
  { id: 61, name: "Kılıç Şövalyesi", image: "assets/tarot/61_kilic_sovalyesi.webp" },
  { id: 62, name: "Kılıç Kraliçesi", image: "assets/tarot/62_kilic_kralicesi.webp" },
  { id: 63, name: "Kılıç Kralı", image: "assets/tarot/63_kilic_kralı.webp" },

  { id: 64, name: "Tılsım Ası", image: "assets/tarot/64_tilsim_asi.webp" },
  { id: 65, name: "Tılsım İkilisi", image: "assets/tarot/65_tilsim_ikilisi.webp" },
  { id: 66, name: "Tılsım Üçlüsü", image: "assets/tarot/66_tilsim_uclusu.webp" },
  { id: 67, name: "Tılsım Dörtlüsü", image: "assets/tarot/67_tilsim_dortlusu.webp" },
  { id: 68, name: "Tılsım Beşlisi", image: "assets/tarot/68_tilsim_beslisi.webp" },
  { id: 69, name: "Tılsım Altılısı", image: "assets/tarot/69_tilsim_altilisi.webp" },
  { id: 70, name: "Tılsım Yedilisi", image: "assets/tarot/70_tilsim_yedilisi.webp" },
  { id: 71, name: "Tılsım Sekizlisi", image: "assets/tarot/71_tilsim_sekizlisi.webp" },
  { id: 72, name: "Tılsım Dokuzlusu", image: "assets/tarot/72_tilsim_dokuzlusu.webp" },
  { id: 73, name: "Tılsım Onlusu", image: "assets/tarot/73_tilsim_onlusu.webp" },
  { id: 74, name: "Tılsım Uşağı", image: "assets/tarot/74_tilsim_usagi.webp" },
  { id: 75, name: "Tılsım Şövalyesi", image: "assets/tarot/75_tilsim_sovalyesi.webp" },
  { id: 76, name: "Tılsım Kraliçesi", image: "assets/tarot/76_tilsim_kralicesi.webp" },
  { id: 77, name: "Tılsım Kralı", image: "assets/tarot/77_tilsim_kralı.webp" }
];

const getTarotById = (id) => tarotDeck.find(card => card.id === id);

module.exports = {
  tarotDeck,
  getTarotById
};